apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/objectiveous-gmail-com/kenpo-vertx:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/objectiveous-gmail-com/kenpo-vertx:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: kenpo-vertx
        chartPath: charts/kenpo-vertx
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/objectiveous-gmail-com/kenpo-vertx"
          image.tag: "{{.TAG}}"
